package Client;

import javax.swing.*;
import java.awt.*;

public class ClientInterface {
    public JPanel mainPanel;
    public JPanel usersPanel;
    public JButton usersUpdateButton;
    public JList usersList;
    public JTextArea eventField;
    public JPanel contentPanel;
    public JPanel sendPanel;
    public JButton sendButton;
    public JTextArea sendTextArea;
    public JScrollPane contentScrollPane;
    public JScrollPane eventScrollPane;
    public JPanel content;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.setPreferredSize(new Dimension(800, 600));
        usersPanel = new JPanel();
        usersPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.add(usersPanel, BorderLayout.WEST);
        usersUpdateButton = new JButton();
        usersUpdateButton.setLabel("Update");
        usersUpdateButton.setText("Update");
        usersPanel.add(usersUpdateButton, BorderLayout.NORTH);
        usersList = new JList();
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        usersList.setModel(defaultListModel1);
        usersPanel.add(usersList, BorderLayout.CENTER);
        sendPanel = new JPanel();
        sendPanel.setLayout(new BorderLayout(0, 0));
        sendPanel.setPreferredSize(new Dimension(119, 200));
        mainPanel.add(sendPanel, BorderLayout.SOUTH);
        sendButton = new JButton();
        sendButton.setText("Send");
        sendPanel.add(sendButton, BorderLayout.EAST);
        sendTextArea = new JTextArea();
        sendTextArea.setLineWrap(false);
        sendTextArea.setMaximumSize(new Dimension(2147483647, 200));
        sendTextArea.setPreferredSize(new Dimension(1, 200));
        sendPanel.add(sendTextArea, BorderLayout.CENTER);
        contentScrollPane = new JScrollPane();
        contentScrollPane.setHorizontalScrollBarPolicy(31);
        mainPanel.add(contentScrollPane, BorderLayout.CENTER);
        contentPanel = new JPanel();
        contentPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        contentScrollPane.setViewportView(contentPanel);
        eventScrollPane = new JScrollPane();
        eventScrollPane.setHorizontalScrollBarPolicy(31);
        mainPanel.add(eventScrollPane, BorderLayout.EAST);
        eventField = new JTextArea();
        eventField.setMinimumSize(new Dimension(200, 26));
        eventField.setPreferredSize(new Dimension(200, 26));
        eventScrollPane.setViewportView(eventField);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    public void createUIComponents() {
//        contentPanel = new JPanel();

//        contentPanel.setLayout(new BoxLayout(contentPanel, BoxLayout.Y_AXIS));
//
//        for (int i = 0; i < 30; i++) {
//            contentPanel.add(new JLabel(String.valueOf(i)));
//        }

        // TODO: place custom component creation code here
    }

    public void clear() {
        contentPanel.removeAll();
        eventField.setText("");
        ((DefaultListModel) usersList.getModel()).clear();
        sendTextArea.setText("");
        mainPanel.revalidate();
        mainPanel.repaint();
    }

}
